# Generated by Django 3.2.9 on 2021-11-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Write_msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urname', models.CharField(max_length=50, null=True)),
                ('urmsg', models.TextField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
    ]
